# Generated by Django 5.0.4 on 2024-04-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_rest_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fistName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Rapper',
        ),
        migrations.DeleteModel(
            name='rest_day',
        ),
    ]
