# Generated by Django 5.0.4 on 2024-04-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_users_delete_rapper_delete_rest_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='companys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
            ],
        ),
    ]
