# Generated by Django 5.0.4 on 2024-04-09 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_companys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='companys',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
