# Generated by Django 5.0.4 on 2024-04-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapi', '0005_delete_companys_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Baseleavedays',
            fields=[
                ('keyid', models.CharField(db_collation='utf8mb4_bin', db_column='KeyID', max_length=36, primary_key=True, serialize=False)),
                ('leavename', models.CharField(db_column='leaveName', max_length=255, unique=True)),
                ('baseday', models.IntegerField()),
                ('upleaveday', models.IntegerField()),
                ('wantfile', models.CharField(db_column='wantFile', max_length=255)),
                ('basedayfile', models.IntegerField(db_column='basedayFile')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'baseleavedays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('keyid', models.CharField(db_collation='utf8mb4_bin', db_column='KeyID', max_length=36, primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'companys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('keyid', models.CharField(db_collation='utf8mb4_bin', db_column='KeyID', max_length=36, primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('keyid', models.CharField(db_collation='utf8mb4_bin', db_column='KeyID', max_length=36, primary_key=True, serialize=False)),
                ('nameofholiday', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('dateofholiday', models.DateTimeField(blank=True, null=True)),
                ('enddateofholiday', models.DateTimeField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'holidays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyapiCompanys',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'myapi_companys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyapiUsers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fistname', models.CharField(db_column='fistName', max_length=100)),
                ('lastname', models.CharField(db_column='lastName', max_length=60)),
            ],
            options={
                'db_table': 'myapi_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('keyid', models.CharField(db_collation='utf8mb4_bin', db_column='KeyID', max_length=36, primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('companyid', models.CharField(db_collation='utf8mb4_bin', db_column='companyId', max_length=36)),
            ],
            options={
                'db_table': 'positions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportLeaves',
            fields=[
                ('keyid', models.CharField(db_collation='utf8mb4_bin', db_column='KeyID', max_length=36, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('squadname', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('leavetype', models.CharField(blank=True, max_length=255, null=True)),
                ('medicalcertificate', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('startdate', models.DateTimeField(blank=True, null=True)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('useleaveday', models.IntegerField(blank=True, null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='phoneNumber', max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('statusfromtl', models.CharField(blank=True, max_length=255, null=True)),
                ('statusofleave', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('remarkfromtl', models.CharField(blank=True, max_length=255, null=True)),
                ('remarkfromhr', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'report_leaves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestInfos',
            fields=[
                ('requestid', models.CharField(db_collation='utf8mb4_bin', max_length=36, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='phoneNumber', max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('firstnameold', models.CharField(blank=True, db_column='firstNameOld', max_length=255, null=True)),
                ('lastnameold', models.CharField(blank=True, db_column='lastNameOld', max_length=255, null=True)),
                ('departmentold', models.CharField(blank=True, db_column='departmentOld', max_length=255, null=True)),
                ('companyold', models.CharField(blank=True, db_column='companyOld', max_length=255, null=True)),
                ('positionold', models.CharField(blank=True, db_column='positionOld', max_length=255, null=True)),
                ('ageold', models.CharField(blank=True, db_column='ageOld', max_length=255, null=True)),
                ('birthdayold', models.DateTimeField(blank=True, db_column='birthdayOld', null=True)),
                ('phonenumberold', models.CharField(blank=True, db_column='phoneNumberOld', max_length=255, null=True)),
                ('addressold', models.CharField(blank=True, db_column='addressOld', max_length=255, null=True)),
                ('emailold', models.CharField(blank=True, db_column='emailOld', max_length=255, null=True)),
            ],
            options={
                'db_table': 'request_infos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestLeaves',
            fields=[
                ('keyid', models.CharField(db_collation='utf8mb4_bin', db_column='KeyID', max_length=36, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('squadname', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('leavetype', models.CharField(blank=True, max_length=255, null=True)),
                ('medicalcertificate', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('startdate', models.DateTimeField(blank=True, null=True)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='phoneNumber', max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('statusfromtl', models.CharField(blank=True, max_length=255, null=True)),
                ('statusofleave', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('remarkfromtl', models.CharField(blank=True, max_length=255, null=True)),
                ('remarkfromhr', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('useleaveday', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'request_leaves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sequelizemeta',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sequelizemeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Squadmembers',
            fields=[
                ('keyid', models.CharField(db_collation='utf8mb4_bin', db_column='KeyID', max_length=36, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'squadmembers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Squads',
            fields=[
                ('squadid', models.CharField(db_collation='utf8mb4_bin', db_column='squadID', max_length=36, primary_key=True, serialize=False)),
                ('squadname', models.CharField(blank=True, max_length=255, null=True)),
                ('departmentid', models.CharField(blank=True, db_column='departmentID', max_length=36, null=True)),
                ('companyid', models.CharField(blank=True, db_column='companyID', max_length=36, null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'squads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('tokenid', models.CharField(db_collation='utf8mb4_bin', max_length=36, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('accesstoken', models.CharField(blank=True, db_column='accessToken', max_length=255, null=True)),
                ('refreshtoken', models.CharField(blank=True, db_column='refreshToken', max_length=255, null=True)),
                ('accesstokenexpiry', models.DateTimeField(blank=True, db_column='accessTokenExpiry', null=True)),
                ('refreshexpiry', models.DateTimeField(blank=True, db_column='refreshExpiry', null=True)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('keyid', models.CharField(db_collation='utf8mb4_bin', db_column='KeyID', max_length=36, primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=255)),
                ('lastname', models.CharField(db_column='lastName', max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('departmentid', models.CharField(db_column='departmentID', max_length=36)),
                ('companyid', models.CharField(db_column='companyID', max_length=36)),
                ('positionid', models.CharField(db_column='positionID', max_length=36)),
                ('age', models.CharField(max_length=255)),
                ('birthday', models.DateTimeField()),
                ('startofworkday', models.DateTimeField(db_column='startOfWorkday')),
                ('phonenumber', models.CharField(db_column='phoneNumber', max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('imgprofile', models.CharField(db_column='imgProfile', max_length=255)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
